# Generated by Django 5.2.16 on 2026-08-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commitments', '0011_commitmentgroup_last_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_links', to='commitments.commitmentgroup')),
            ],
        ),
    ]
