# Generated by Django 5.2.16 on 2026-07-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
