# Generated by Django 5.2.16 on 2026-07-30 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0003_category_status_commitment_due_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="CommitmentGroup",
        ),
        migrations.RenameField(
            model_name="commitment",
            old_name="category",
            new_name="group",
        ),
        migrations.AlterModelOptions(
            name="commitmentgroup",
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="commitmentgroup",
            name="description",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="commitmentgroup",
            name="information_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="commitmentgroup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
