# Generated by Django 5.2.16 on 2026-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0004_commitmentgroup_remove_commitment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
