# Generated by Django 5.2.16 on 2026-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0005_alter_commitmentgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='contract_and_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='notice_period_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitment',
            name='payment_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_off', 'One-off')], max_length=20),
        ),
    ]
