# Generated by Django 5.2.16 on 2026-07-30 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0006_commitment_amount_commitment_contract_and_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitment',
            old_name='contract_and_date',
            new_name='contract_end_date',
        ),
    ]
