# Generated by Django 5.2.16 on 2026-07-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0007_rename_contract_and_date_commitment_contract_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='payment_status',
            field=models.CharField(choices=[('not_applicable', 'Not_applicable'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='not_applicable', max_length=20),
        ),
    ]
