# Generated by Django 5.2.16 on 2026-07-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0008_commitment_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('default_provider_name', models.CharField(blank=True, max_length=200)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_payment_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('one_off', 'One-off')], max_length=20)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='commitments.commitmentgroup')),
            ],
            options={
                'ordering': ['group__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_template_name_per_group')],
            },
        ),
    ]
