# Generated by Django 5.2.16 on 2026-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0010_seed_commitment_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentgroup',
            name='last_reviewed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
