# Generated by Django 5.2.16 on 2026-08-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0011_commitmentgroup_last_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitmentgroup',
            name='information_url',
        ),
    ]
