# Generated by Django 5.2.16 on 2026-08-11 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0012_remove_commitmentgroup_information_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commitmenttemplate',
            options={'ordering': ['group__name', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='default_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='commitments.status'),
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='default_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='recommended_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='commitmenttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commitmenttemplate',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='commitmenttemplate',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
