# Generated by Django 5.2.16 on 2026-08-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0014_seed_commitment_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
