# Generated by Django 5.2.16 on 2026-08-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0015_alter_commitment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='commitments.commitmenttemplate'),
        ),
    ]
