# Generated by Django 5.2.16 on 2026-08-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0017_commitmenttemplateexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='last_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
