# Generated by Django 5.2.16 on 2026-08-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitments', '0019_commitmentpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='last_paid_at',
        ),
    ]
